# fly.toml app configuration file generated for api-gateway-young-butterfly-2076 on 2024-10-05T09:44:58+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-gateway-young-butterfly-2076'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
